### ISSUE TITLE
n //= 10

### ISSUE THREAD

**Issue by Christinezy** [Andrewlearning/Leetcoding#13]
https://github.com/Andrewlearning/Leetcoding/blob/f73b84e3a6c68681c1df46df8e2fa0c4bbdb67ac/leetcode/Math/202m.%20%E5%BF%AB%E4%B9%90%E6%95%B0.py#L44

**Comment by Andrewlearning** [comment]
In `python3`:

```
>>> a = 19
>>> a /= 10
>>> a
1.9
```

In `python2`:
```
>>> a = 19
>>> a /= 10
>>> a
1
```

Therefore, in `python2` can use `n /= 10`.
