### ISSUE TITLE
right 扫过的元素 一定存在在counter里，所以不用再次判断了

### ISSUE THREAD

**Issue by Christinezy** [Andrewlearning/Leetcoding#15]
https://github.com/Andrewlearning/Leetcoding/blob/f73b84e3a6c68681c1df46df8e2fa0c4bbdb67ac/leetcode/Array/%E6%BB%91%E5%8A%A8%E7%AA%97%E5%8F%A3/76.%20%E6%9C%80%E5%B0%8F%E8%A6%86%E7%9B%96%E5%AD%90%E4%B8%B2(%E6%BB%91%E5%8A%A8%E7%AA%97%E5%8F%A3).py#L49

**Comment by Andrewlearning** [comment]
ok, just leave it there.
