### ISSUE TITLE
这里要分来写，先判断index是否越界，再判断是不是活（==1 or == 2)

### ISSUE THREAD

**Issue by Christinezy** [Andrewlearning/Leetcoding#17]
https://github.com/Andrewlearning/Leetcoding/blob/f73b84e3a6c68681c1df46df8e2fa0c4bbdb67ac/leetcode/DFS%26BFS/289.%20%E7%94%9F%E5%91%BD%E6%B8%B8%E6%88%8F.py#L53

**Comment by Andrewlearning** [comment]
Writing them together is fine.
