### ISSUE TITLE
更优的写法

### ISSUE THREAD

**Issue by Christinezy** [Andrewlearning/Leetcoding#19]
https://github.com/Andrewlearning/Leetcoding/blob/33621735447ee8bdb1750b35de9e92859ad0bd1c/leetcode/Matrix/73.%20%E7%9F%A9%E9%98%B5%E7%BD%AE%E9%9B%B6.py#L38

'''
class Solution(object):
    def setZeroes(self, matrix):
        """
        :type matrix: List[List[int]]
        :rtype: None Do not return anything, modify matrix in-place instead.
        """

        #单独记录第一行/列有无0
        firstRow = False
        firstCol = False

        m = len(matrix)
        n = len(matrix[0])

        #记录第一行是否有0
        for i in range(n):
            if matrix[0][i] == 0:
                firstRow = True

        #记录第一列是否有0
        for i in range(m):
            if matrix[i][0] == 0:
                firstCol = True

        #用矩阵的第一行/列记录对应的行/列是否有0
        for i in range(1, m):
            for j in range(1, n):
                if matrix[i][j] == 0:
                    matrix[0][j] = 0
                    matrix[i][0] = 0

        #在第一行里查找，如果某一列出现0，整一列为0
        for i in range(1, n):
            if matrix[0][i] == 0:
                for j in range(1, m):
                    matrix[j][i] = 0

        #在第一列里查找，如果第一行出现0，整一行为0
        for i in range(1, m):
            if matrix[i][0] == 0:
                for j in range(1, n):
                    matrix[i][j] = 0

        #除了第一行，第一列，其他的格子都遍历完毕
        #开始遍历第一行，只要出现了0，第一行都为0
        if firstRow:
            for j in range(n):
                matrix[0][j] = 0

        #开始遍历第一列，只要出现了0，第一列都为0
        if firstCol:
            for i in range(m):
                matrix[i][0] = 0
        return matrix

'''
(原地算法) O(nm)
我们只需统计出矩阵中每一行或者每一列是否有0，然后把含有0的行或者列都置成0即可。

用两个变量记录第一行和第一列是否有0。
遍历整个矩阵，用矩阵的第一行和第一列记录对应的行和列是否有0。
把含有0的行和列都置成0。

时间复杂度分析：矩阵中每个元素只遍历常数次数，所以时间复杂度是 (nm)。
空间复杂度分析：只用了两个额外的变量记录第一行和第一列是否含有0，
所以额外的空间复杂度是 (1)，满足原地算法的要求。
'''

'''

**Comment by Andrewlearning** [comment]
我觉得我的写法比较好记一点
